#!/bin/sh
#
# Initramfs-tools hook script
#
# Copyright 2006 Tim Dijstra <tim@famdijkstra.org>
# Released under GPLv2

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

if [ ! -x /usr/lib/uswsusp/resume -o ! -f /etc/uswsusp.conf ] ; then
    exit 0;
fi

# The only obligatory option ..
RES_DEV=$(sed -rn 's/^resume device[[:space:]]+[:=][[:space:]]+// p' /etc/uswsusp.conf)

if [ -z "$RES_DEV" ] || [ ! -b $RES_DEV ]; then
    exit 0;
fi

if grep -q '^splash[[:space:]]*[:=][[:space:]]*[yY]' /etc/uswsusp.conf; then
    CURRENT_THEME=$(sed -rn 's/.*<current_theme>[[:space:]]*(.*)[[:space:]]*<\/current_theme>.*/\1/ p' /etc/splashy/config.xml)
    mkdir -p "${DESTDIR}/etc/splashy/themes/$CURRENT_THEME"

    cp /etc/splashy/config.xml "${DESTDIR}/etc/splashy/"
    cp "/etc/splashy/themes/$CURRENT_THEME"/* "${DESTDIR}/etc/splashy/themes/$CURRENT_THEME/"

	for L in libdirectfb_fbdev.so libdirectfb_keyboard.so libdirectfbwm_default.so libidirectfbimageprovider_jpeg.so libidirectfbimageprovider_gif.so libidirectfbimageprovider_png.so libidirectfbfont_ft2.so libidirectfbfont_default.so ; do

        	I=$(find /usr/lib/directfb-/ -name $L)
        	[ -n "$I" ] || continue
        	mkdir -p $DESTDIR$(dirname $I)
        	copy_exec $I .`dirname $I`
	done
fi

copy_exec /usr/lib/uswsusp/resume /sbin
cp /etc/uswsusp.conf "$DESTDIR/etc" 
